services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  server:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
    command: npm run start:dev
volumes:
  db_data: